# NAME: Proxy for Loon
# AUTHOR: zhuziyi
# REPO: https://github.com/zhuziyi1989/tools/blob/master/loon/rule/
# UPDATED: 2026-03-04 16:47:01
# TOTAL: 9
DOMAIN-SUFFIX,itangtalk.com 
DOMAIN-SUFFIX,note.com
DOMAIN-SUFFIX,fox59.com
DOMAIN-SUFFIX,bigme.pro
DOMAIN,translate.googleapis.com
DOMAIN,translate.google.com
DOMAIN,translate-pa.googleapis.com
DOMAIN-SUFFIX,tradingview.com
DOMAIN,cn.tradingview.com